In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

np.int64(8)

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [14]:
slice_of_arr = arr[0:5]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
slice_of_arr[:] = 99

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [24]:
arr_copy = arr.copy()

In [25]:
arr_copy[:] = 100

In [26]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr_2d = np.array([[5,10,15], [20, 25, 30], [35, 40, 45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d.shape

(3, 3)

In [32]:
arr_2d[0]

array([ 5, 10, 15])

In [33]:
arr_2d[2]

array([35, 40, 45])

In [34]:
arr_2d[1][1]

np.int64(25)

In [35]:
arr_2d[1,1]

np.int64(25)

In [36]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [37]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [39]:
arr = np.arange(1,11)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
bool_arr = arr > 4

In [43]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr = np.arange(0 ,10)

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [50]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
arr / arr

/tmp/ipykernel_16405/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [53]:
1 / arr

/tmp/ipykernel_16405/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [54]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [55]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [56]:
np.log(arr)

/tmp/ipykernel_16405/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [57]:
arr.sum()

np.int64(45)

In [58]:
arr.mean()

np.float64(4.5)

In [59]:
arr.max()

np.int64(9)

In [60]:
arr.var()

np.float64(8.25)

In [61]:
arr.std()

np.float64(2.8722813232690143)

In [65]:
arr2d = np.arange(0, 25).reshape(5, 5)

In [66]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
arr2d.shape

(5, 5)

In [68]:
arr2d.sum()

np.int64(300)

In [69]:
arr2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [70]:
arr2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])