In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [5]:
type(np.array(my_list))

numpy.ndarray

In [6]:
my_arr = np.array(my_list)

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(5,5)

array([[0.54737392, 0.4464461 , 0.40382179, 0.62986518, 0.15899773],
       [0.04141561, 0.12708874, 0.52396038, 0.94772814, 0.31539989],
       [0.65955056, 0.81533633, 0.47876742, 0.92345797, 0.36478256],
       [0.15940994, 0.24198362, 0.70667948, 0.5088542 , 0.7261242 ],
       [0.88116312, 0.62974344, 0.34655154, 0.9048891 , 0.75108286]])

In [24]:
np.random.randn(3,4)

array([[-0.27597411, -1.23925437, -0.59157909,  0.85122273],
       [-0.99865753, -0.4910752 , -0.68831476, -0.53003894],
       [-0.01706021, -0.37759195,  0.4066525 , -0.29960856]])

In [28]:
np.random.randint(0, 101, (4,5))

array([[ 30,  84,  33,  82,  86],
       [ 92,  53,  78,  79,  11],
       [ 43,  63,  84,  64, 100],
       [ 12,  95,  66,  39,  22]])

In [30]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
arr = np.arange(0,25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ran_arr = np.random.randint(0, 101, 10)

In [35]:
ran_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [36]:
ran_arr.max()

np.int64(99)

In [37]:
ran_arr.min()

np.int64(2)

In [38]:
ran_arr.argmax()

np.int64(5)

In [39]:
ran_arr.argmin()

np.int64(7)

In [40]:
ran_arr.dtype

dtype('int64')

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.shape

(25,)

In [43]:
arr = arr.reshape(5,5)

In [44]:
arr.shape

(5, 5)

In [46]:
arr = arr.reshape(25,1)

In [47]:
arr.shape

(25, 1)